

# Stop all running containers
- name: Obtain running containters info
  become: yes
  docker_host_info:
    containers: yes
  register: containers

- name: Stop all running containers
  become: yes
  docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ containers.containers | map(attribute='Id') | list }}"

# Check if the data folder exist, if so,  create a new directory
- name: Checking data folders
  become: yes
  stat:
    path: "{{ item.dir }}"
  register: directory_stats
  with_items:
    - "{{ node_info }}"

- name: Create data directory
  become: yes
  file:
    path: "{{ item.item.dir }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"


# Create and Run couchdb container
- name: Create and start CouchDB Docker container
  become: yes
  docker_container:
    name: 'couchdb-{{item.ip}}'
    image: "ibmcom/couchdb3:{{ VERSION }}"
    state: started
    timeout: 60
    recreate: true
    pull: yes
    volumes:
      - '{{item.dir}}'
    env:
      COUCHDB_USER: "{{ usr }}"
      COUCHDB_PASSWORD: "{{ pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ item.ip }}\""
  loop: '{{node_info}}'



# Create and Run couchdb container
- name: Create master
  become: yes
  docker_container:
    name: 'couchdb-{{item.ip}}'
    image: "ibmcom/couchdb3:{{ VERSION }}"
    state: started
    timeout: 60
    recreate: true
    pull: yes
    ports: '{{item.ports}}'
    volumes:
      - '{{item.dir}}'
    env:
      COUCHDB_USER: "{{ usr }}"
      COUCHDB_PASSWORD: "{{ pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ item.ip }}\""
  loop: '{{master_info}}'