# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: id_rsa_ccc
instance_flavor: uom.mse.2c9g


# Security group
security_groups:
  - name: ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: open_range
    description: "Open range for testing"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0


# Volumes
# 1: common storage
# 2: docker
volumes:
  - vol_name: instance01-vol-common
    vol_size: 100
  - vol_name: instance01-vol-docker
    vol_size: 100
  # - vol_name: instance02-vol-common
  #   vol_size: 10
  # - vol_name: instance02-vol-docker
  #   vol_size: 10
  # - vol_name: instance03-vol-common
  #   vol_size: 10
  # - vol_name: instance03-vol-docker
  #   vol_size: 10
  # - vol_name: instance04-vol-common
  #   vol_size: 10
  # - vol_name: instance04-vol-docker
  #   vol_size: 10

# Instance
instances:
  - name: instance01
    volumes: ['instance01-vol-common', 'instance01-vol-docker']
  # - name: instance02
  #   volumes: ['instance02-vol-common', 'instance02-vol-docker']
  # - name: instance03
  #   volumes: ['instance03-vol-common', 'instance03-vol-docker']
  # - name: instance04
  #   volumes: ['instance04-vol-common', 'instance04-vol-docker']